### ISSUE TITLE
Invisible Character at the End of URLs

### ISSUE THREAD

**Issue by agmm** [rnegron/noticias-pr-cli#116]
La función `terminalLink`está añadiendo un caracter invisible al final de algunos enlaces. Específicamente, está añadiendo un espacio de ancho cero (e2 80 8b).

Nota: Comportamiento observado usando el terminal de VSCode.

## Ejemplo

Obtenido:
`https://www.elnuevodia.com/noticias/politica/nota/someNews/%E2%80%8B`

Esperado:
`https://www.elnuevodia.com/noticias/politica/nota/someNews/`

**Comment by rnegron** [comment]
Interesante, voy a intentar reproducir este bug. Gracias por reportarlo!

**Comment by agmm** [comment]
El bug parece venir directamente de la librería `terminal-link` como tal. Usan `\u200B` para separar el URL de los paréntesis.

```js
return typeof options.fallback === 'function' ? options.fallback(text, url) : `${text} (\u200B${url}\u200B)`;
```

Un quick fix sería cambiando la línea anterior por esto:

```js
return typeof options.fallback === 'function' ? options.fallback(text, url) : `${text} ${url}`;
```

**Comment by rnegron** [comment]
Efectivamente, 

```javascript
encodeURI('\u200B') === '%E2%80%8B'
```

Entonces parece que es un tema sobre el terminal de VSCode no formando parte de los [supported terminals](https://gist.github.com/egmontkob/eb114294efbcd5adb1944c9f3cb5feda#supporting-apps). De todas formas, voy a subir un PR que añade un fallback a `terminal-link` a ver si soluciona el problema.
